package(default_visibility = ["//visibility:public"])

java_library(
    name = "lib",
    srcs = glob(["src/main/java/com/mycompany/*.java"]),
    deps = [
        #        "//thirdparty/com/google/inject:guice",
        #        #  "//thirdparty/io/netty:netty_tcnative_boringssl_static_jar_linux_x86_64",
        #        #  "//thirdparty/io/netty:netty_transport_native_epoll_jar_linux_x86_64",
        #        "//thirdparty/org/jooby",
        #        "//thirdparty/org/jooby:funzy",
        #        "//thirdparty/org/jooby:jooby_netty",
        "//thirdparty/org/jooby:jooby_netty",
        "//thirdparty/org/jooby",
        "//thirdparty/org/jooby:funzy",
        "//thirdparty/org/javassist",
        "//thirdparty/io/netty:netty_transport_native_epoll_jar_linux_x86_64",
        "//thirdparty/io/netty:netty_tcnative_boringssl_static_jar_linux_x86_64",
        "//thirdparty/io/netty:netty_codec_http2",
        "//thirdparty/io/netty:netty_handler",
        "//thirdparty/io/netty:netty_codec_http",
        "//thirdparty/io/netty:netty_codec",
        "//thirdparty/io/netty:netty_transport",
        "//thirdparty/io/netty:netty_resolver",
        "//thirdparty/io/netty:netty_buffer",
        "//thirdparty/io/netty:netty_common",
        "//thirdparty/com/typesafe:config",
        "//thirdparty/com/google/inject/extensions:guice_multibindings",
        "//thirdparty/com/google/inject:guice",
        "//thirdparty/javax/inject:javax_inject",
        "//thirdparty/com/google/guava",
        "//thirdparty/org/codehaus/mojo:animal_sniffer_annotations",
        "//thirdparty/org/checkerframework:checker_qual",
        "//thirdparty/com/google/j2objc:j2objc_annotations",
        "//thirdparty/com/google/errorprone:error_prone_annotations",
        "//thirdparty/com/google/code/findbugs:jsr305",
        "//thirdparty/ch/qos/logback:logback_classic",
        "//thirdparty/org/slf4j:slf4j_api",
        "//thirdparty/ch/qos/logback:logback_core",
    ],
)

java_binary(
    name = "app",
    main_class = "com.mycompany.App",
    runtime_deps = [":lib"],
)
